WebGames.MVC/Controllers/GenresController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebGames.Application.GameGenre.Queries.GetAllGamesOfGenre;
using WebGames.Application.GameGenre.Queries.GetAllGenresOfGame;
using WebGames.Application.Genre.Commands.CreateGenre;
using WebGames.Application.Genre.Commands.DeleteGenre;
using WebGames.Application.Genre.Commands.EditGenre;
using WebGames.Application.Genre.Queries.GetAllGenres;
using WebGames.Application.Genre.Queries.GetGenreByEncodedName;
using WebGames.MVC.Extensions;

namespace WebGames.MVC.Controllers
{
    public class GenresController : Controller
    {
        private readonly IMediator mediator;
        private readonly IMapper mapper;

        public GenresController(IMediator mediator, IMapper mapper)
        {
            this.mediator = mediator;
            this.mapper = mapper;
        }

        [Route("all-genres")]
        public async Task<IActionResult> Index()
        {
            var genres = await mediator.Send(new GetAllGenresQuery());
            return View(genres);
        }

        [Route("genre/{encodedName}")]
        public async Task<IActionResult> IndexGenre(string encodedName)
        {
            var games = await mediator.Send(new GetAllGamesOfGenreQuery(encodedName));
            
            if (games == null)
            {
                return View(null);
            }

            foreach (var game in games)
            {
                var genres = await mediator.Send(new GetAllGenresOfGameQuery(game.EncodedName));
                game.Genres = genres;
            }
            return View(games);
        }

        [Route("genre/create")]
        [Authorize(Roles = "Admin, Moderator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("genre/create")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Create(CreateGenreCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);

            this.SetNotification("success", "Success!", $"Created genre: {model.Name}");

            return RedirectToAction(nameof(Index));
        }

        [Route("genre/{encodedName}/edit")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(string encodedName)
        {
            var dto = await mediator.Send(new GetGenreByEncodedNameQuery(encodedName));

            EditGenreCommand model = mapper.Map<EditGenreCommand>(dto);
            return View(model);
        }

        [HttpPost]
        [Route("genre/{encodedName}/edit")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(EditGenreCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);
            return RedirectToAction(nameof(Index));
        }

        [Route("genre/{encodedName}/delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Delete(string encodedName)
        {
            var dto = await mediator.Send(new GetGenreByEncodedNameQuery(encodedName));

            DeleteGenreCommand model = mapper.Map<DeleteGenreCommand>(dto);
            return View(model);
        }

        [HttpPost]
        [Route("genre/{encodedName}/delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Delete(DeleteGenreCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebGames.MVC/Controllers/WebGamesController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebGames.Application.Game.Commands.CreateGame;
using WebGames.Application.Game.Commands.DeleteGame;
using WebGames.Application.Game.Commands.EditGame;
using WebGames.Application.Game.Queries.GetAllGames;
using WebGames.Application.Game.Queries.GetGameByEncodedName;
using WebGames.Application.GameGenre.Commands.AddGenreToGame;
using WebGames.Application.GameGenre.Commands.RemoveGenreFromGame;
using WebGames.Application.GameGenre.Queries.GetAllGenresOfGame;
using WebGames.Application.GameGenre.Queries.GetAllGenresOfGameExcludingExisting;
using WebGames.Application.Genre.Queries.GetAllGenres;
using WebGames.MVC.Extensions;

namespace WebGames.MVC.Controllers
{
    public class WebGamesController : Controller
    {
        private readonly IMediator mediator;
        private readonly IMapper mapper;

		public WebGamesController(IMediator mediator, IMapper mapper)
        {
            this.mediator = mediator;
            this.mapper = mapper;
		}

        public async Task<IActionResult> Index()
        {
            var games = await mediator.Send(new GetAllGamesQuery());
            foreach (var game in games)
            {
                var genres = await mediator.Send(new GetAllGenresOfGameQuery(game.EncodedName));
                game.Genres = genres;
            }
            return View(games);
        }

        public IActionResult NoAccess()
        {
            return View();
        }

        [Route("Home")]
        public IActionResult Logout()
        {
            return RedirectToAction(nameof(Index));
        }

        [Route("{encodedName}")]
        public async Task<IActionResult> Play(string encodedName)
        {
            var dto = await mediator.Send(new GetGameByEncodedNameQuery(encodedName));
            return View(dto);
        }

        [Route("{encodedName}/edit")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(string encodedName)
        {
            var dto = await mediator.Send(new GetGameByEncodedNameQuery(encodedName));

            var genres = await mediator.Send(new GetAllGenresQuery());

            EditGameCommand model = mapper.Map<EditGameCommand>(dto);
            model.AllGenres = genres;

            return View(model);
        }

        [HttpPost]
        [Route("{encodedName}/edit")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(EditGameCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);
            return RedirectToAction(nameof(Index));
        }

        [Route("{encodedName}/delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Delete(string encodedName)
        {
            var dto = await mediator.Send(new GetGameByEncodedNameQuery(encodedName));

            DeleteGameCommand model = mapper.Map<DeleteGameCommand>(dto);
            return View(model);
        }

        [HttpPost]
        [Route("{encodedName}/delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Delete(DeleteGameCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin, Moderator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Create(CreateGameCommand model)
        {
            if (ModelState.IsValid == false) return View(model);

            await mediator.Send(model);

            this.SetNotification("success", "Success!", $"Created game: {model.Name}");

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        [Route("WebGames/AddGenreToGame/{genreEncodedName}/{gameEncodedName}")]
        public async Task<IActionResult> AddGenreToGame(string genreEncodedName, string gameEncodedName)
        {
            var model = new AddGenreToGameCommand() { GameEncodedname = gameEncodedName, GenreEncodedname = genreEncodedName };
            await mediator.Send(model);
            return Ok();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        [Route("WebGames/RemoveGenreFromGame/{genreEncodedName}/{gameEncodedName}")]
        public async Task<IActionResult> RemoveGenreFromGame(string genreEncodedName, string gameEncodedName)
        {
            var model = new RemoveGenreFromGameCommand() { GameEncodedname = gameEncodedName, GenreEncodedname = genreEncodedName };
            await mediator.Send(model);
            return Ok();
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Moderator")]
        [Route("WebGames/{encodedName}/GetGenres")]
        public async Task<IActionResult> GetGenresOfGame(string encodedName)
        {
            var data = await mediator.Send(new GetAllGenresOfGameQuery(encodedName));

            return Ok(data);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Moderator")]
        [Route("WebGames/{encodedName}/GetAllGenresExcludingExisting")]
        public async Task<IActionResult> GetAllGenresExcludingExistingOfGame(string encodedName)
        {
            var data = await mediator.Send(new GetAllGenresOfGameExcludingExistingQuery(encodedName));

            return Ok(data);
        }
    }
}

WebGames.MVC/Views/Shared/_IndexGamesPartial.cshtml
@model IEnumerable<WebGames.Application.Game.GameDto>?
@{
    foreach (var item in Model!)
    {
        <div class="card m-3 card-hover h-50" style="width: 18rem;" asp-controller="WebGames" asp-action="Play" asp-route-encodedName="@item.EncodedName">
        @if (item.ImageName != null)
            {
                <img class="card-img-top" src="~/gameImages/@item.ImageName" alt="Card image cap" style="max-height: 175px;">
            }
        else
        {
                <img class="card-img-top" src="@item.ImageSource" alt="Card image cap" style="max-height: 175px;">
        }
            <div class="card-body">
                <h5 class="card-title text-dark">@item.Name</h5>
                <p class="card-text d-sm-block" style="min-height: 50px;">@item.Description</p>
                <div class="m-1" style="z-index:3; position:relative; align-self: center;">
                    @foreach (var genre in item.Genres)
                    {
                        <a class="btn badge bg-info text-light" data-bs-toggle="tooltip" data-bs-title="@genre.Description" style="text-decoration:none" asp-controller="Genres" asp-action="IndexGenre" asp-route-encodedName="@genre.EncodedName">@genre.Name</a>
                    }
                </div>
                <br />
                <a class="btn btn-primary col-md-12 stretched-link " asp-controller="WebGames" asp-action="Play" asp-route-encodedName="@item.EncodedName"><i class="bi bi-play-circle-fill"></i> Play</a>
            </div>
            @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
            {
                <div style="z-index:3; position:relative; align-self: center;" class="card-footer">
                    <a class="btn btn-secondary" asp-controller="WebGames" asp-action="Edit" asp-route-encodedName="@item.EncodedName"><i class="bi bi-gear-fill"></i> Edit</a>
                </div>
            }
        </div>
    }
}

WebGames.MVC/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;
@{
    var action = ViewContext.RouteData.Values["Action"]?.ToString();
    var controller = ViewContext.RouteData.Values["Controller"]?.ToString();
    var notification = TempData["Notification"] != null ? JsonConvert.DeserializeObject<Notification>(TempData["Notification"]!.ToString()!)! : null;
    var userContext = ViewContext.HttpContext.User;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebGames.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="WebGames" asp-action="Index">Web Games</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link @(controller == "WebGames" && action == "Index" ? "active" : "")" asp-area="" asp-controller="WebGames" asp-action="Index">All Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(controller == "Genres" && action == "Index" ? "active" : "")" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web Games - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @if (notification != null)
    {
        <script>
            toastr["@notification.Type"]("@notification.Message", "@notification.Title")
        </script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebGames.MVC/Views/Shared/_ModerationPanelPartial.cshtml
@{
@if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
{
    <div class="card">
        <div class="card-header">
            Moderation Panel
        </div>
        <div class="card-body">
            <h5 class="card-title">Welcome, @User.Identity?.Name!</h5>
            <a asp-controller="WebGames" asp-action="Create" class="btn btn-primary col-md-3">New GAME</a>
            <a asp-controller="Genres" asp-action="Create" class="btn btn-secondary col-md-3">New GENRE</a>
        </div>
    </div>
}
}